//   Copyright 2020 Vircadia Contributors
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
'use strict'

import { Config } from '@Base/config';

import { AuthToken } from '@Entities/AuthToken';
import { TokenScope } from '@Entities/TokenScope';
import { createObject, getObject, getObjects, updateObjectFields, deleteMany, deleteOne } from '@Tools/Db';

import { GenericFilter } from '@Entities/EntityFilters/GenericFilter';
import { CriteriaFilter } from '@Entities/EntityFilters/CriteriaFilter';

import { VKeyedCollection } from '@Tools/vTypes';
import { GenUUID, IsNullOrEmpty, IsNotNullOrEmpty } from '@Tools/Misc';
import { Logger } from '@Tools/Logging';

export let tokenCollection = 'tokens';

// Initialize token management.
// Mostly starts a periodic function that deletes expired tokens.
export function initTokens(): void {
  // Expire tokens that have pased their prime
  setInterval( async () => {
    const nowtime = new Date();
    const deleteInfo = await deleteMany(tokenCollection, { tokenExpirationTime: { $lt: nowtime } } );
    const deletedTokens = deleteInfo.deletedCount;
    if (typeof(deletedTokens) === 'number' && deletedTokens > 0) {
      Logger.debug(`Tokens.Expiration: expired ${deletedTokens} tokens`);
    };
  }, 1000 * 60 * 5 );
};

export const Tokens = {
  // Create a new AuthToken.
  async createToken(pAccountId: string, pScope: string[], pExpireHours: number = 0): Promise<AuthToken> {
    const aToken = new AuthToken();
    aToken.tokenId = GenUUID();
    aToken.token = GenUUID();
    aToken.refreshToken = GenUUID();
    aToken.accountId = pAccountId;
    // Verify that passed scopes are known scope codes
    aToken.scope = [];
    pScope.forEach( aScope => {
      if (TokenScope.KnownScope(aScope)) aToken.scope.push(aScope);
    });
    aToken.tokenCreationTime = new Date();
    aToken.tokenExpirationTime = Tokens.computeDefaultExpiration(aToken.scope, aToken.tokenCreationTime);
    return aToken;
  },
  async getTokenWithTokenId(pTokenId: string): Promise<AuthToken> {
    return IsNullOrEmpty(pTokenId) ? null : getObject(tokenCollection, { 'tokenId': pTokenId });
  },
  async getTokenWithToken(pToken: string): Promise<AuthToken> {
    return IsNullOrEmpty(pToken) ? null : getObject(tokenCollection, { 'token': pToken });
  },
  async getTokenWithRefreshToken(pToken: string): Promise<AuthToken> {
    return IsNullOrEmpty(pToken) ? null : getObject(tokenCollection, { 'refreshToken': pToken });
  },
  async addToken(pAuthToken: AuthToken) : Promise<AuthToken> {
    return createObject(tokenCollection, pAuthToken);
  },
  async removeToken(pAuthToken: AuthToken) : Promise<any> {
    return deleteOne(tokenCollection, { 'tokenId': pAuthToken.tokenId });
  },
  async updateTokenFields(pEntity: AuthToken, pFields: VKeyedCollection): Promise<AuthToken> {
    return updateObjectFields(tokenCollection, { tokenId: pEntity.tokenId }, pFields);
  },
  // Return all the tokens that were generated by a specific accountId
  async *getTokensForOwner(pOwnerId: string, pPager?: CriteriaFilter): AsyncGenerator<AuthToken> {
    return IsNullOrEmpty(pOwnerId)
            ? null
            : Tokens.enumerateAsync(new GenericFilter({ 'accountId': pOwnerId }), pPager);
  },
  async *enumerateAsync(pFilter?: CriteriaFilter, pPager?: CriteriaFilter, pScoper?: CriteriaFilter): AsyncGenerator<AuthToken> {
    for await (const tok of getObjects(tokenCollection, pFilter, pPager, pScoper)) {
      yield tok;
    };
    // return getObjects(tokenCollection, pFilter, pPager, pScoper); // not sure why this does't work
  },
  // Return an expiration date for the token depending on its scope
  computeDefaultExpiration(pScopes: string[], pBaseDate?: Date): Date {
    return new Date((pBaseDate ? pBaseDate.valueOf() : new Date().valueOf())
          + ( TokenScope.HasScope(pScopes, TokenScope.DOMAIN)
                   ? Config.auth["domain-token-expire-hours"] * 1000*60*60
                   : Config.auth["owner-token-expire-hours"] * 1000*60*60
            )
    );
  },
  // Return 'true' if the passed token has not expired.
  hasNotExpired(pAuthToken: AuthToken): boolean {
    return IsNullOrEmpty(pAuthToken)
        ? false
        : pAuthToken.tokenExpirationTime.valueOf() > new Date().valueOf();
  }
};
